__all__ = [
    "LOG_LEVEL",
    "NULL_LOGGER",
    "BLogger",
    "ILogger",
    "LogLevel",
    "TXLogger",
    "XLogger",
]
from pathlib import Path
from typing import Literal

from .trait import ILogger, LogLevel

type LOG_LEVEL = Literal["NULL", "FATAL", "ERROR", "WARN", "BRIEF", "INFO", "DEBUG"]

NULL_LOGGER: ILogger

class BLogger(ILogger):
    def __init__(
        self,
        level: (LogLevel | LOG_LEVEL),
    ) -> None: ...
    @property
    def level(self) -> LogLevel: ...
    def flush(self) -> None: ...
    def print(self, *msg: object, level: LogLevel = ...) -> None: ...
    def disp(self, *msg: object, end: Literal["\n", "\r", "\x1b[1K\r", ""] = "\n") -> None: ...
    def debug(self, *msg: object) -> None: ...
    def info(self, *msg: object) -> None: ...
    def brief(self, *msg: object) -> None: ...
    def warn(self, *msg: object) -> None: ...
    def error(self, *msg: object) -> None: ...
    def fatal(self, *msg: object) -> None: ...
    def exception(self, e: Exception) -> Exception: ...

class XLogger(ILogger):
    def __init__(
        self,
        level: (LogLevel | LOG_LEVEL),
        file: str | Path | None = None,
    ) -> None: ...
    @property
    def level(self) -> LogLevel: ...
    def flush(self) -> None: ...
    def print(self, *msg: object, level: LogLevel = ...) -> None: ...
    def disp(self, *msg: object, end: Literal["\n", "\r", ""] = "\n") -> None: ...
    def debug(self, *msg: object) -> None: ...
    def info(self, *msg: object) -> None: ...
    def brief(self, *msg: object) -> None: ...
    def warn(self, *msg: object) -> None: ...
    def error(self, *msg: object) -> None: ...
    def fatal(self, *msg: object) -> None: ...
    def exception(self, e: Exception) -> Exception: ...

class TXLogger(ILogger):
    def __init__(
        self,
        level: (LogLevel | LOG_LEVEL),
        file: str | Path | None = None,
    ) -> None: ...
    @property
    def level(self) -> LogLevel: ...
    def flush(self) -> None: ...
    def print(self, *msg: object, level: LogLevel = ...) -> None: ...
    def disp(self, *msg: object, end: Literal["\n", "\r", ""] = "\n") -> None: ...
    def debug(self, *msg: object) -> None: ...
    def info(self, *msg: object) -> None: ...
    def brief(self, *msg: object) -> None: ...
    def warn(self, *msg: object) -> None: ...
    def error(self, *msg: object) -> None: ...
    def fatal(self, *msg: object) -> None: ...
    def exception(self, e: Exception) -> Exception: ...
