from typing import Literal, overload

import numpy as np

from pytools.arrays import A1, A2, A3
from pytools.result import Result

def householder_orthogonal_basis[F: np.floating](v: A1[F]) -> A2[F]: ...
@overload
def orthonormal_basis[F: np.floating](a: A1[F], b: A1[F], *, flatten: Literal[True]) -> A2[F]: ...
@overload
def orthonormal_basis[F: np.floating](a: A1[F], b: A1[F], *, flatten: Literal[False]) -> A1[F]: ...
@overload
def r_basis[F: np.floating](v: A1[F]) -> Result[A2[F]]: ...
@overload
def r_basis[F: np.floating](v: A2[F]) -> Result[A3[F]]: ...
